# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0214e7a2ab61adc56660cd2f566b3aac667cf49bbdd4801f0f199a8f35724d76160dab855ff4230fe37b7f8140d057707564cd8ff83ce28a1d95d56ac56bb201

test:
  secret_key_base: eddad082bc2bf595a7fc2c52f17c261e9616517d9bf8ef86a61e75f0392e4ad9a6c09c489ae51d7f56e6ba1c1280a4a2b8d7915325ad6829c852548d159fa5b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
